### ISSUE TITLE
Integrate with MTM's DOD service

### ISSUE THREAD

**Issue by saebekassebil** [Notalib/LYT#678]
I'll try to keep track of how the testing/integration with MTM's DOD service is going, here.
## Functionality 
 - [x] Login functionality
 - [x] Playback of a book (with known ID)
 - [x] Showing a Content List
 - [x] Searching (Using Dynamic Menus)
 - [x] Play from Content List
 - [x] Show book details
 - [ ] Save bookmarks (Can only save `<lastmark>`)

## Gotchas (MTM *bugs*):
  - Looks like the `id` attr of `getContentList` should be a child node `<id>`
  - Bookmarking does work - but is disabled because of what seems to be a major bug on the MTM server. For now, only `<lastmark>` is saved
  - A book can only be issued when *it is already* on your "bookshelf". You can add stuff to your bookshelf with Dynamic Menus (`questionID="addToBookshelf"`)

## Commits of general interest

  - 50884c9626ed1547562052496f7facd2a2a3bd4a - Make autocompletion optional
  - df2ca1fb3e85f88f435d2d1bd8f6ac9a9dca17f5 - Remove deprecated getDetails method of Book
  - d46e5e9775e2eb5271ce59a62b49ceed85c8216a - Support attributes on JSON2XML function
  - 6078c9b862f12cf4fa03ab35a19cc7f385444e8d - (Dynamic Menues) Implement protocol for getQuestions

**Current Status**: Playback of a book works. Both from the bookshelf and by giving a direct ID. This only works thru a proxy at the moment, because the servers we get resources from doesn't support CORS headers.

## Todo

  - [ ] Merge the `mtm` branch into `master`, and make sure everything still works against m.e17.dk

**Comment by saebekassebil** [comment]
This is pretty much done. Continued work will be tracked in separate issues.
